import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/about">Go to about</Link>
          <Link href="/">Go home</Link>
        </nav>
        {children}
        </body>
    </html>
  )
}
